# version: "3"
services:
  mongo:
    container_name: mongo-bridge-network-mern
    image: mongo
    restart: always
    ports:
      - "27017"
    networks:
      - default
    volumes:
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    env_file:
      - ./backend/.env.production
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: node-bridge-network-mern
    build:
      context: ./backend
      dockerfile: docker-setup/node/production/Dockerfile
    networks:
      - default
      - frontend
    volumes:
      - ./backend:/home/node/app
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "5000:4000"

  frontend:
    container_name: react-bridge-network-mern
    build:
      context: ./frontend
      dockerfile: docker-setup/react/production/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    name: backend-bridge-network-mern
  frontend:
    name: frontend-bridge-network-mern
